name: Build and test

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches-ignore:
      - 'update_dependencies'
jobs:
  dev-zip:
    name: Build ZIP and upload to s3
    if: github.event.pull_request.draft == false && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.retrieve-branch-name.outputs.branch_name }}
      git-sha-8: ${{ steps.retrieve-git-sha-8.outputs.sha8 }}
    steps:
      - name: Check out source files
        uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Configure Composer cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install composer deps
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest
      - name: Create zip
        run: yarn run dist
      - name: Retrieve branch name
        id: retrieve-branch-name
        run: echo "::set-output name=branch_name::$(REF=${GITHUB_HEAD_REF:-$GITHUB_REF} && echo ${REF#refs/heads/} | sed 's/\//-/g')"
      - name: Retrieve git SHA-8 string
        id: retrieve-git-sha-8
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Upload Latest Version to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_DEV_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: artifact/
          DEST_DIR: ${{ github.event.pull_request.base.repo.name }}-${{ steps.retrieve-branch-name.outputs.branch_name }}-${{ steps.retrieve-git-sha-8.outputs.sha8 }}/

  comment-on-pr:
    name: Comment on PR with links to plugin ZIPs
    if: ${{ github.head_ref && github.head_ref != null }}
    runs-on: ubuntu-latest
    needs: dev-zip
    env:
      CI: true
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    outputs:
      pr_number: ${{ steps.get-pr-number.outputs.num }}
      comment_body: ${{ steps.get-comment-body.outputs.body }}
    steps:
      - name: Get PR number
        id: get-pr-number
        run: echo "::set-output name=num::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"

      - name: Check if a comment was already made
        id: find-comment
        uses: peter-evans/find-comment@v1
        with:
          issue-number: ${{ steps.get-pr-number.outputs.num }}
          comment-author: github-actions[bot]
          body-includes: Download [build]

      - name: Get comment body
        id: get-comment-body
        run: |
          body="Plugin build for ${{ github.event.pull_request.head.sha }} is ready :bellhop_bell:!
          - Download [build](https://verti-artifacts.s3.amazonaws.com/${{ github.event.pull_request.base.repo.name }}-${{ needs.dev-zip.outputs.branch-name }}-${{ needs.dev-zip.outputs.git-sha-8 }}/neve.zip)"
          body="${body//$'\n'/'%0A'}"
          echo "::set-output name=body::$body"
      - name: Create comment on PR with links to plugin builds
        if: ${{ steps.find-comment.outputs.comment-id == '' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.get-pr-number.outputs.num }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update comment on PR with links to plugin builds
        if: ${{ steps.find-comment.outputs.comment-id != '' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: ${{ steps.get-comment-body.outputs.body }}
  e2e:
    name: E2E for ${{ matrix.specs }} on ${{ matrix.envs }}
    needs: dev-zip
    strategy:
      matrix:
        include:
          ## Amp specs needs just one machine
          - machines: 1
            specs: "amp"
            envs: "amp"
          ## Dashboard specs needs one machine
          - machines: 1
            specs: "dashboard"
            envs: "default"
          ## 2 machines for classic editor tests
          - machines: 1
            specs: "editor/classic"
            envs: "classic-editor"
          - machines: 2
            specs: "editor/classic"
            envs: "classic-editor"
          ## 2 machines for modern editor (Gutenberg)
          - machines: 1
            specs: "editor/modern"
            envs: "default"
          - machines: 2
            specs: "editor/modern"
            envs: "default"
          ## 6 machines for customizer tests
          - machines: 1
            specs: "customizer"
            envs: "sample-data"
          - machines: 2
            specs: "customizer"
            envs: "sample-data"
          - machines: 3
            specs: "customizer"
            envs: "sample-data"
          - machines: 4
            specs: "customizer"
            envs: "sample-data"
          - machines: 5
            specs: "customizer"
            envs: "sample-data"
          - machines: 6
            specs: "customizer"
            envs: "sample-data"
    runs-on: ubuntu-latest
    env:
      ZIP_URL: "https://verti-artifacts.s3.amazonaws.com/${{ github.event.pull_request.base.repo.name }}-${{ needs.dev-zip.outputs.branch-name }}-${{ needs.dev-zip.outputs.git-sha-8 }}/neve.zip"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        name: Restore WP environment cache
        with:
          path: ~/.wp-content
          key: ${{ runner.os }}-wpcore-${{ hashFiles('bin/envs/**/*.sh') }}
      - uses: actions/cache@v1
        name: Restore Cypress cached binary
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        name: Restore Yarn cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install ${{ matrix.envs }} env for ${{ matrix.specs }} specs
        run: bash ./bin/envs/init.sh ${{ matrix.envs }} latest no "$ZIP_URL"
      - name: Run ${{ matrix.specs }} Cypress tests
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        uses: cypress-io/github-action@v1
        with:
          env: host=localhost,port=8080
          browser: chrome
          headless: true
          parallel: true
          group: e2e-${{ matrix.specs }}
          record: true
          spec: cypress/integration/${{ matrix.specs }}/**/*,
